server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:enversDB
    driverClassName: org.h2.Driver
    username: sa
    password: sa123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui


