server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/envers
    driverClassName: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
expert:
  app:
    jwtSecret: expertClubSecretKey
    jwtExpirationMs: 86400000